<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Aphorisms extends Model
{
    /**
     * Связанная с моделью таблица.
     */
    protected $table = 'aphorisms';
    /**
     * Разрешаем добавлять данные к полям
     */
    protected $fillable = ['body', 'authors_id', 'categorys_id'];
    /**
     * Получить Теги.
     */
    public function getTags()
    {
        return $this->hasMany('App\AphorismsTags');
    }
    /**
     * Получить Автора.
     */
    public function getAuthor()
    {
        return $this->belongsTo('App\AphorismsAuthors');
    }

    public function __get($key)
    {
        return parent::__get($key); // TODO: Change the autogenerated stub
    }
}
